# Generated by Django 6.1.2 on 2026-10-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_categoria_options_alter_evento_options_and_more'),
        ('home', '0002_role'),
    ]

    operations = [
    ]
